In [1]:
import numpy as np

### 1. Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [2]:
mat1 = np.array(np.random.randint(1,10,9)).reshape(3,3)
mat2 = np.array(np.random.randint(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[8 9 5]
 [1 2 4]
 [2 3 6]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[1 8 6]
 [2 7 6]
 [2 4 3]]

Addition
------------------
 [[ 9 17 11]
 [ 3  9 10]
 [ 4  7  9]]

Multiplication
------------------
 [[ 8 72 30]
 [ 2 14 24]
 [ 4 12 18]]

Division
------------------
 [[8.         1.125      0.83333333]
 [0.5        0.28571429 0.66666667]
 [1.         0.75       2.        ]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[22 11  3]
 [-1 -8  0]
 [ 2  1 12]]

Addition of a scalar (100)
-------------------------
 [[108 109 105]
 [101 102 104]
 [102 103 106]]

Exponentiation, matrix cubed here
----------------------------------------
 [[512 729 125]
 [  1   8  64]
 [  8  27 216]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[2.82842712 3.         2.23606798]
 [1.         1.41421356 2.        ]
 [1.414213

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

### 2. Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [3]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[3 3 2]
 [8 9 2]
 [2 7 2]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[9 5 4]
 [8 8 9]
 [6 6 4]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 38

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [13 19  6]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 8 19 11]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 18 144  28]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [432 240 144]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.222222222222222

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [4]:
##Solution
import numpy as np
from numpy.random import randint as ri
mat1 = np.array(ri(1,100,9)).reshape(9,1)
mat1

array([[89],
       [98],
       [17],
       [24],
       [81],
       [16],
       [57],
       [92],
       [24]])

### 4. Sort

In [5]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))


Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [40 24 77 55 73  7 17 16 61 29]

Here is the sorted vector
 -------------------------------------------------- 
 [ 7 16 17 24 29 40 55 61 73 77]


In [6]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[51 64 17 54 86]
 [18 19 29 46 34]
 [86 83 99 21 46]
 [10 38 70 74 64]
 [11 70 35 35 34]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[17 51 54 64 86]
 [18 19 29 34 46]
 [21 46 83 86 99]
 [10 38 64 70 74]
 [11 34 35 35 70]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[10 19 17 21 34]
 [11 38 29 35 34]
 [18 64 35 46 46]
 [51 70 70 54 64]
 [86 83 99 74 86]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [7]:
from numpy.random import randint as ri
a=ri(1,100,10)
b=ri(5,50,10)
c=ri(7,200,10)
print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:", b.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

print("Max of a:", a.min())
print("Max of b:", b.min())


print("Max of a location:", a.argmin())
print("Max of b location:", b.argmin())
print("Max of c location:", b.argmin())



a: [ 4 62 71 55  6 89 93 98 26 24]
b: [16 28 25 41 48  6 25 23 26 12]
c: [173 115  23 137  42  62  15  30 172  69]
Max of a: 98
Max of b: 48
Max of a location: 7
Max of b location: 4
Max of c location: 4
Max of a: 4
Max of b: 6
Max of a location: 0
Max of b location: 5
Max of c location: 5


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [8]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 4 9]
 [5 7 8]
 [3 8 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 6 1]
 [4 6 4]
 [3 1 8]]

Sq-root of 1st matrix using np
------------------
 [[1.73205081 2.         3.        ]
 [2.23606798 2.64575131 2.82842712]
 [1.73205081 2.82842712 2.23606798]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[  20.08553692   54.59815003 8103.08392758]
 [ 148.4131591  1096.63315843 2980.95798704]
 [  20.08553692 2980.95798704  148.4131591 ]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.47712125 0.60205999 0.95424251]
 [0.69897    0.84509804 0.90308999]
 [0.47712125 0.90308999 0.69897   ]]

Modulo reminder using np
 -------------------------------------------------- 
 [[3 4 0]
 [1 1 0]
 [0 0 5]]


### 7.Generating matrices from distributions

In [9]:
import numpy as np
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.95013661 0.57526002 0.72903302]
 [0.94357734 0.73248785 0.77407379]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.83927885  0.21927799  0.27149323]
 [-1.5399117   0.17067126  0.34860365]
 [ 1.14918256 -0.83250207 -0.5653682 ]
 [ 0.81201868  1.29069264  0.35369896]]
Random integer vector: [22  4 41 64 63 71 44 85 47 87]

Random integer matrix
[[78 29 58 33]
 [23 87 59 17]
 [97 50 66 30]
 [17  1 16 49]]

20 samples drawn from a dice throw: [2 5 1 6 3 6 4 4 2 3 5 4 2 1 5 6 1 5 5 5]


### 8.Find the nearest value from a given number in an array using NumPy.

In [10]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

import numpy as np
x = np.random.uniform(1, 12, 5)
print(x)
print("\nInput array\n","-"*50,"\n",x)
v = 4
n = x[np.abs(x - v).argmin()]
print(n)

[10.90303685  4.35467515  5.89802578 10.47043212  7.45929856]

Input array
 -------------------------------------------------- 
 [10.90303685  4.35467515  5.89802578 10.47043212  7.45929856]
4.354675152432661


In [11]:
x.flat[3]

10.470432117376404

#### 9. Write code using numpy to produce following output
* [[0 0 0]
 [0 1 2]
 [0 2 4]]

In [12]:
import numpy as np
print(np.fromfunction(lambda i, j: i*j, (3, 3), dtype=int))

[[0 0 0]
 [0 1 2]
 [0 2 4]]
